apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-zibx
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkwch-fix-0075-0046-tenant/tkwch-fix-0075-0046-app/devfile-sample-zibx@sha256:3e4436bc086714e27e4915ad63a396a9f7e7030402d38ed9465193ff8ff31a64
        name: my-nodejs
        resources: {}
status: {}
